import 'package:flutter/material.dart';

import '../../app_color.dart';

class ColorSchemeLight {
  /// Light Theme ColorScheme
  ColorScheme get getTheme => const ColorScheme(
        brightness: Brightness.light,
        primary: AppColor.primary,
        onPrimary: AppColor.onPrimary,
        primaryContainer: AppColor.primaryContainer,
        onPrimaryContainer: AppColor.onPrimaryContainer,
        primaryFixed: AppColor.primaryFixed,
        primaryFixedDim: AppColor.primaryFixedDim,
        onPrimaryFixed: AppColor.onPrimaryFixed,
        onPrimaryFixedVariant: AppColor.onPrimaryFixedVariant,
        secondary: AppColor.secondary,
        onSecondary: AppColor.onSecondary,
        secondaryContainer: AppColor.secondaryContainer,
        onSecondaryContainer: AppColor.onSecondaryContainer,
        secondaryFixed: AppColor.secondaryFixed,
        secondaryFixedDim: AppColor.secondaryFixedDim,
        onSecondaryFixed: AppColor.onSecondaryFixed,
        onSecondaryFixedVariant: AppColor.onSecondaryFixedVariant,
        tertiary: AppColor.tertiary,
        onTertiary: AppColor.onTertiary,
        tertiaryContainer: AppColor.tertiaryContainer,
        onTertiaryContainer: AppColor.onTertiaryContainer,
        tertiaryFixed: AppColor.tertiaryFixed,
        tertiaryFixedDim: AppColor.tertiaryFixedDim,
        onTertiaryFixed: AppColor.onTertiaryFixed,
        onTertiaryFixedVariant: AppColor.onTertiaryFixedVariant,
        error: AppColor.error,
        onError: AppColor.onError,
        errorContainer: AppColor.errorContainer,
        onErrorContainer: AppColor.onErrorContainer,
        surface: AppColor.surface,
        onSurface: AppColor.onSurface,
        surfaceDim: AppColor.surfaceDim,
        surfaceBright: AppColor.surfaceBright,
        surfaceContainerLowest: AppColor.surfaceContainerLowest,
        surfaceContainerLow: AppColor.surfaceContainerLow,
        surfaceContainer: AppColor.surfaceContainer,
        surfaceContainerHigh: AppColor.surfaceContainerHigh,
        surfaceContainerHighest: AppColor.surfaceContainerHighest,
        onSurfaceVariant: AppColor.onSurfaceVariant,
        outline: AppColor.outline,
        outlineVariant: AppColor.outlineVariant,
        shadow: AppColor.shadow,
        scrim: AppColor.scrim,
        inverseSurface: AppColor.inverseSurface,
        onInverseSurface: AppColor.onInverseSurface,
        inversePrimary: AppColor.inversePrimary,
        surfaceTint: AppColor.surfaceTint,
      );
}
